### ISSUE TITLE
Unable to relocate images to registry dockerhub

### ISSUE THREAD

**Issue by balloray** [pivotal/docs-tap#1129]
Hello,
I am in the process of installing Tanzu Application Platform using the link below from vmware.
I tried to relocate images to (dockerhub) registry as adviced in the steps  but I keep getting error.

![image](https://user-images.githubusercontent.com/63379157/166715214-a0e62ed1-2110-4922-8b01-03f702e83945.png)

![image](https://user-images.githubusercontent.com/63379157/166711682-52e13565-1739-4339-9efb-e25e3374fd2a.png)

**Comment by YugangW** [comment]
This was intended for all installation as well as airgap. See @krisapplegate if you need additional context.

**Comment by balloray** [comment]
I was able to confirm Dockerhub still works with Tanzu Application Platform
