### ISSUE TITLE
catalog-info.yaml file section of VSCode setup guide mentions workload.yaml

### ISSUE THREAD

**Issue by mikegehard** [pivotal/docs-tap#1495]
Page: https://docs-staging.vmware.com/en/draft/VMware-Tanzu-Application-Platform/1.3/tap/GUID-vscode-extension-getting-started.html#the-cataloginfoyaml-file-4

![image](https://user-images.githubusercontent.com/128210/188737585-e1d73883-027d-4c92-aca6-19b9dc715836.png)

**Comment by snneji** [comment]
This issue has been resolved.
