### ISSUE TITLE
`ceip_policy_disclosed` is duplicated in the first tap-values.yaml example

### ISSUE THREAD

**Issue by Manifaust** [pivotal/docs-tap#1604]
It shows up twice in the same snippet in the [install page](https://docs-staging.vmware.com/en/draft/VMware-Tanzu-Application-Platform/1.3/tap/GUID-install.html#install-your-tanzu-application-platform-profile-1). Once as

```
ceip_policy_disclosed: true 
```

and the second time

```
ceip_policy_disclosed: FALSE-OR-TRUE-VALUE # Installation fails if this is not set to true. Not a string.
```

**Comment by YugangW** [comment]
Thank you @Manifaust for pointing this out. 
Looks like this issue was introduced by [PR 1547](https://github.com/pivotal/docs-tap/pull/1547). @mdc81 could you please help verify? Thanks.

**Comment by mdc81** [comment]
@YugangW yes, it is repeated in deep. Please keep the first entry and modify it to look exactly as below: 

ceip_policy_disclosed: FALSE-OR-TRUE-VALUE # Installation fails if this is not set to true. Not a string.

**Comment by YugangW** [comment]
Thanks @mdc81. The change has been made in the staging: https://docs-staging.vmware.com/en/draft/VMware-Tanzu-Application-Platform/1.3/tap/GUID-install.html#full-profile-2
Closing this issue.
