### ISSUE TITLE
broken link to Configure Tap GUI

### ISSUE THREAD

**Issue by Manifaust** [pivotal/docs-tap#1605]
In [Accessing TAP GUI](https://docs-staging.vmware.com/en/draft/VMware-Tanzu-Application-Platform/1.3/tap/GUID-tap-gui-accessing-tap-gui.html).

There's link to Configure Tanzu Application Platform GUI section `../install.html#configure-tap-gui` but that anchor no longer exists.

There are other docs with that heading though:
* set-up-tap-gui-rbac-eks
* set-up-tap-gui-rbac-gke

**Comment by RichardJJG** [comment]
Thanks for pointing this out, @Manifaust. I'll delete the cross-reference because it's not essential and it's no longer clear where the link should really target.
