### ISSUE TITLE
Collect deprecations within the release notes

### ISSUE THREAD

**Issue by scothis** [pivotal/docs-tap#1806]
TAP 1.3.0 includes a handful of deprecations in the [release notes](https://docs.vmware.com/en/VMware-Tanzu-Application-Platform/1.3/tap/GUID-release-notes.html#v130-0) spread across multiple components and sections. There's no summary of depreciations. As a user, this makes it difficult to know what is capabilities of a release I should avoid depending on, or migrate away from.

For example:
- `Tanzu CLI - Apps plug-in` has a deprecations subsection with a bulleted list within the `New features` heading.
- `Tanzu Build Service` and `Services Toolkit` mix new features and deprecations in a bulleted list, also within the `New features` heading.
- `Supply Chain Security Tools` and `Application Single Sign-On` list deprecations under `Breaking changes`

**Proposal:** Add a `Deprecations` section to the release notes that collects the component level deprecations from other parts of the release notes. Deprecations from previous releases should continue to be listed until they are removed, at which time it should move to the breaking changes section.

**Comment by snneji** [comment]
Hi @scothis, thanks for your feedback. We are currently looking into the release notes template to refine and improve it. This is a great suggestion that we'll take into consideration during that effort. We hope to implement the new template in TAP 1.3.2 or 1.4.0 at the latest.

**Comment by snneji** [comment]
This issue is done: https://docs.vmware.com/en/VMware-Tanzu-Application-Platform/1.5/tap/release-notes.html#deprecations-11
