### ISSUE TITLE
Add package repo Step 3 INSTALL_REPO unclear when relocation skipped

### ISSUE THREAD

**Issue by Petahhh** [pivotal/docs-tap#1955]
In this page https://docs-staging.vmware.com/en/draft/VMware-Tanzu-Application-Platform/1.4/tap/GUID-install.html under the "Add the Tanzu Application Platform package repository" in step 3, it refers to an INSTALL_REPO.

Given the INSTALL_REPO is described in the previous optional section, it is not clear what it should be for people who skip the relocation section. It should be `tanzu_application_platform`

**Comment by YugangW** [comment]
Hi @Petahhh, Thanks for your feedback. Please feel free to send in a PR to address the mentioned concern against `main` branch. I will cherry-pick it to all the previous versions where applicable. Thanks.

**Comment by snneji** [comment]
Resolved by https://jira.eng.vmware.com/browse/TAAP-533
