### ISSUE TITLE
Tanzu CLI Package commands/flags/behaviors/output will change and docs need to be updated accordingly

### ISSUE THREAD

**Issue by heyjcollins** [pivotal/docs-tap#1986]
This work should be done for TAP 1.5

The new `package` plugin will be distributed with Tanzu CLI core `v0.28.0`, which TAP will pick up from the next TKG "Glasgow" release `v2.1.0` which is slated to GA on January 17th, 2023.

There are a large number of `tanzu package` references in docs-tap that need to be reviewed and updated to accurately reflect the changes to the `package` plugin.

For example, the `tanzu package available list` command output will no longer include the `SHORT-DESCRIPTION` column so all instances where example output from that command is provided in docs will need to be updated to reflect that.
Note - this just one of many minor changes in the plugin that require docs-tap changes.

Comprehensive before vs. after changes are documented [**here**](https://hackmd.io/DZbCaWqSQwK11MxZr-caDg?view) 

I've grep'd for all references to the commands in docs-tap and attached the output of those greps to a comment here for your convenience.

**Comment by heyjcollins** [comment]
[package-available-get.txt](https://github.com/pivotal/docs-tap/files/10190616/package-available-get.txt)
[package-available-list.txt](https://github.com/pivotal/docs-tap/files/10190617/package-available-list.txt)
[package-repository-add.txt](https://github.com/pivotal/docs-tap/files/10190618/package-repository-add.txt)
[package-repository-list.txt](https://github.com/pivotal/docs-tap/files/10190619/package-repository-list.txt)
[package-repository-update.txt](https://github.com/pivotal/docs-tap/files/10190620/package-repository-update.txt)

**Comment by heyjcollins** [comment]
@BarrAndrea

**Comment by snneji** [comment]
Jira issue marked as done: https://jira.eng.vmware.com/browse/TAAP-543

Closing the issue.
