### ISSUE TITLE
Incorrect TKG details in Prerequisites

### ISSUE THREAD

**Issue by KeithRichardLee** [pivotal/docs-tap#21]
For beta 1 docs, replace 

"For Tanzu Kubernetes Grid, ensure that you are using Tanzu Kubernetes Grid v1.14.0 or later. Clusters of this version have kapp-controller v0.20.0 pre-installed."

with

"For Tanzu Kubernetes Grid, ensure that you are using Tanzu Kubernetes Grid v1.4.0 or later. Clusters of this version have kapp-controller v0.23.0 pre-installed."

**Comment by jncd** [comment]
@KeithRichardLee 
Oh dear. The QA team wasn't paying attention here.

Thanks very much for calling my attention to this. (Fixed now.)
