### ISSUE TITLE
External-Secrets: Add supported providers to external-secrets docs.

### ISSUE THREAD

**Issue by seagomezar** [pivotal/docs-tap#2239]
This work should be done for TAP 1.5

The supported providers in external-secrets should be present, adding a better understanding of the options we support for creating and listing secrets.

Upstream docs for reference: https://external-secrets.io/v0.7.2/introduction/stability-support/

**Comment by HenryBorys** [comment]
@seagomezar Are you going to submit a PR with the changes you want?

**Comment by seagomezar** [comment]
Yes! The team is working on that.
