### ISSUE TITLE
Beta 2 Docs - No separate section for TKGm 1.4.0 installation, while TCE 0.91 has a separate section.

### ISSUE THREAD

**Issue by vdesikanvmware** [pivotal/docs-tap#334]
TKGm installation is handled in the in the page Installing Part I: Prerequisites, EULA, and CLI, while we have a separate section for Installing on a Tanzu Community Edition v0.9.1 Cluster. We need to maintain consistency with the way we  document.

**Comment by BarrAndrea** [comment]
@vdesikanvmware I agree it should be in one place. Do you think it should be in the "Installing Part I: Prerequisites, EULA, and CLI" or the "Tanzu Community Edition v0.9.1 Cluster" section?

**Comment by vdesikanvmware** [comment]
@BarrAndrea - Sorry. I just saw your comment now. I see that this is now addressed properly. Do you still have any question for me?

**Comment by BarrAndrea** [comment]
@vdesikanvmware No more questions for you. Since this has been addressed I am going to close this issue.
