### ISSUE TITLE
Suggestion, use a different name for the instance of 'tanzu-java-web-app'

### ISSUE THREAD

**Issue by kdvolder** [pivotal/docs-tap#342]
See: https://vmware.slack.com/archives/C01G0P79LSE/p1635362254035800?thread_ts=1635333832.024200&cid=C01G0P79LSE

In the interest of conceptual clarity I think it might be better to have the instructions use different name for the instantiated template. I.e. personally I am/was having a lot of confusion between the things / concepts that are more like 'instances' versus the things that are more like 'types / classes / templates'. Naming the instance of the template the same as the template itself 'tanzu-java-web-app' doesn't help there at all. So instead of 'tanzu-java-web-app' maybe it could be called 'my-first-tanzu-app' or something like that. Thereby it would be clear that 

a) you could pick a different name if you wanted to
b) you could instantiate the template multiple times 
c) each time you do that you are in fact creating a new and distinct app/component.

**Comment by BarrAndrea** [comment]
Closing issue due to the team not having the bandwidth for this decision. The team will submit a new issue when there is bandwidth for this decision.
