### ISSUE TITLE
Suggestion: Provide values for all the profile types

### ISSUE THREAD

**Issue by msrinivasssa** [pivotal/docs-tap#346]
@mpriamo 
[install.md](https://github.com/pivotal/docs-tap/blob/main/install.md#-install-a-tanzu-application-platform-profile) at step 3 shows a sample values yaml where to install full profile, `profile:full` needs to be provided. 
it would be good to mention what value to provide to install other profiles Developer Light. Shared Tools and Operator Light

**Comment by a-peek4** [comment]
@msrinivasssa Can you confirm that the changes below are correct?

1. Install the package by running:

    ```bash
    tanzu package install tap -p tap.tanzu.vmware.com -v 0.3.0 --values-file tap-values.yml -n tap-install profile:full
    ```

**Comment by msrinivasssa** [comment]
> @msrinivasssa Can you confirm that the changes below are correct?
> 
> 1. Install the package by running:
>    ```shell
>    tanzu package install tap -p tap.tanzu.vmware.com -v 0.3.0 --values-file tap-values.yml -n tap-install profile:full
>    ```

@a-peek4 the above CLI is not correct. My comments were already addressed here. 

> \<PROFILE-VALUE> is a value such as full or dev-light
