### ISSUE TITLE
Include name space tap-install in the sample installation for Learning center

### ISSUE THREAD

**Issue by msrinivasssa** [pivotal/docs-tap#351]
[install learning center](https://github.com/pivotal/docs-tap/blob/main/install-components.md#-install-learning-center) step-3 Install Learning Center operator, include namespace `-n tap-install`. Since earlier instructions to add the repo in `tap-install` ns, package will be available only on that namespace. Hence, this current instruction to install learning center on default ns won't work

**Comment by a-peek4** [comment]
Hi @msrinivasssa Can you confirm that the following changes I made to the section you pointed out are correct?


    ```shell
    tanzu package install learning-center --package-name learningcenter.tanzu.vmware.com --version 1.0.14-build.1 -f learning-center-config.yaml
    ```

    The command above will create a namespace called `tap-install` in your Kubernetes cluster,
    and the operator along with any required namespaced resources is created in it.
    A set of custom resource definitions and a global cluster role binding are also created.
    The list of resources you see being created are:

1. Install Learning Center Operator by running:    
```shell
    customresourcedefinition.apiextensions.k8s.io/workshops.training.eduk8s.io created
    customresourcedefinition.apiextensions.k8s.io/workshopsessions.training.eduk8s.io created
    customresourcedefinition.apiextensions.k8s.io/workshopenvironments.training.eduk8s.io created
    customresourcedefinition.apiextensions.k8s.io/workshoprequests.training.eduk8s.io created
    customresourcedefinition.apiextensions.k8s.io/trainingportals.training.eduk8s.io created
    serviceaccount/eduk8s created
    customresourcedefinition.apiextensions.k8s.io/systemprofiles.training.eduk8s.io created
    clusterrolebinding.rbac.authorization.k8s.io/eduk8s-cluster-admin created
    deployment.apps/eduk8s-operator created
    ```

    You can check that the operator deployed successfully by running:

    ```shell
    kubectl get all -n tap-install
    ```

    The Pod for the operator should be marked as running.

**Comment by russeta** [comment]
Hello, @msrinivasssa:  Wanted to check to see if you have had the chance to view these changes.  Can you confirm they are correct?  Thank you! @russeta

**Comment by msrinivasssa** [comment]
Looks good to me. Thanks.
