### ISSUE TITLE
Remove "TAP" and "TKG" from docs

### ISSUE THREAD

**Issue by KeithRichardLee** [pivotal/docs-tap#38]
TAP and TKG are not a legally recognized names for VMware Tanzu Application Catalog and VMware Tanzu Kubernetes Grid. Please remove "TAP"and "TKG" from docs unless this is an allowed exception.

**Comment by mpriamo** [comment]
I agree with this one. No acronyms.

**Comment by jncd** [comment]
Let's do a global pass at the end, there'll be lots more TAPs added as people make PRs. I've made a story inour tracker so this doesn't get lost: https://www.pivotaltracker.com/story/show/179775934
