### ISSUE TITLE
Add detailed prerequisites

### ISSUE THREAD

**Issue by KeithRichardLee** [pivotal/docs-tap#39]
Add detailed prerequisites. Collate validated prerequisites from each Eng team. An example would be...

- Tanzu Net account
- Internet access from host and k8s cluster (call out dark site install not supported yet or similar)
- List of URLs that need to be reached from cluster and also from workstation eg network.pivotal.io, registry.pivotal.io, github, dockerhub etc
- Flux (for App Acc)
- An image registry (for TBS and for petclinic images for tutorial) with a min of 7GB free
- a git repo (plus creds/token)
- git client
- carvel tools

**Comment by mpriamo** [comment]
Thank you for elaborating on this. Have asked Stephen Levine and Ben Hale to take a look at our pre-reqs and cluster config as well. Will send this over to them.

**Comment by snneji** [comment]
Looks like this has been completed (and is super old). @YugangW can you confirm and close. Thanks!
