### ISSUE TITLE
Add links to our own products eg TKG

### ISSUE THREAD

**Issue by KeithRichardLee** [pivotal/docs-tap#40]
In the doc it calls out "Tanzu Kubernetes Grid", please add link to its doc page.

**Comment by mpriamo** [comment]
Considering we won't be supporting TKG in Beta2, we could probably ignore this for now.

**Comment by thesteve0** [comment]
Was this fixed?

**Comment by YugangW** [comment]
Xref to TKG docs added to: https://docs-staging.vmware.com/en/draft/VMware-Tanzu-Application-Platform/1.6/tap/prerequisites.html
