### ISSUE TITLE
Broken Link in Components

### ISSUE THREAD

**Issue by billkable** [pivotal/docs-tap#479]
Link for [Services Toolkit](https://docs.vmware.com/en/Services-Toolkit/0.4/services-toolkit-0-4/GUID-overview.html) is broken.

Should this be for [v3](https://docs.vmware.com/en/SCP-Toolkit/0.3/scp-toolkit-0-3/GUID-overview.html)?

**Comment by jncd** [comment]
Hi @billkable 
Yes, I believe you are correct. The 0.4 version does not yet appear on TanzuNet. (I'm surprised that the 0.4 docs are already on docs.vmware.com.) @RobC55 and I have updated the link and will push to prod.

**Comment by jncd** [comment]
Hi @billkable, 
Apparently, we're wrong. Although v0.4.0 is not available on Tanzu Net, it is part of the TAP v0.3 beta. 
I learned this from the PM, Srikanth: "version 0.4.0 is not on tanzu net but the package bundle will be with TAP beta 3 repository."
