### ISSUE TITLE
Source Controller component documentation and troubleshooting sub-page should be included in release beta3 and greater

### ISSUE THREAD

**Issue by heyjcollins** [pivotal/docs-tap#517]
My team recently added `Source Controller` component documentation to docs-tap.
I see them in beta4 staging, but not in the beta3 docs.
They should be displayed in beta3+.

Can you please make the updates as required?

Here are the two pages in question (and they should also show up in the beta3+ TOC):
https://docs-staging.vmware.com/en/VMware-Tanzu-Application-Platform/0.4/tap-0-4/GUID-source-controller-about.html
https://docs-staging.vmware.com/en/VMware-Tanzu-Application-Platform/0.4/tap-0-4/GUID-source-controller-troubleshooting.html

**Comment by jncd** [comment]
Hi @heyjcollins 

Those changes were PRed to the main branch — and there were no instructions in the PR comments about adding to the beta-3 branch. Under those circumstances, we have to assume that the PR author intended for the changes to appear only in main branch. 

However, I'll copy those two files and the toc entry to the beta-3 branch and republish asap.

**Comment by jncd** [comment]
Done: https://docs.vmware.com/en/VMware-Tanzu-Application-Platform/0.3/tap-0-3/GUID-source-controller-about.html
