### ISSUE TITLE
Callout to replace TANZU-NET-USER and TANZU-NET-PASSWORD in yaml files with users creds

### ISSUE THREAD

**Issue by KeithRichardLee** [pivotal/docs-tap#52]
Throughout the doc, need to call out to replace "TANZU-NET-USER" and "TANZU-NET-PASSWORD" in the yaml files with user credentials.

Suggest also to change name depending on final destination of where the packages will land eg if "registry.vmware.com" then "Tanzu Net" is not intuitive.

**Comment by jncd** [comment]
@msrinivasssa @dhadukk 
Could you follow up on this? 
I thought that "TANZU-NET-USER" and "TANZU-NET-PASSWORD" are your user credentials  https://network.tanzu.vmware.com 

I'm not familiar with "registry.vmware.com" (the term isn't used in the beta-2 docs.

**Comment by msrinivasssa** [comment]
@jncd @KeithRichardLee 
Removal of "TANZU-NET-USER" and "TANZU-NET-PASSWORD" in the yaml files  are already addressed. 
As far registry.tanzu.vmware.com, the credentials are same as Tanzunet. Hence, it is mentioned that way.

**Comment by jncd** [comment]
Super. Thanks @msrinivasssa 
I'll close this issue now.
