### ISSUE TITLE
Add verify steps to end of install steps

### ISSUE THREAD

**Issue by KeithRichardLee** [pivotal/docs-tap#54]
Eg "Install Cloud Native Runtimes" add step 5 on how to verify install (tanzu package installed list -n tap-install) or add note that will be verified later. As a reader I started an install and am now moving on to install something else without known the previous install was successful!

**Comment by jncd** [comment]
You're absolutely right. I've made a story to address this: https://www.pivotaltracker.com/story/show/179776616
