### ISSUE TITLE
Provide all required yamls 

### ISSUE THREAD

**Issue by KeithRichardLee** [pivotal/docs-tap#55]
Several times throughout the doc the user has to create yaml files and copy and paste the contents in from the doc. This is wide open to error and slows down the install process. All required yamls should be provided in package/repo or similar.

**Comment by jncd** [comment]
Sounds good to me @KeithRichardLee 
But, this isn't a docs issue _per se_ — this would rest with the PMs to decide on and the engineering teams to implement. @valealaria

I'll keep this request in mind and try to raise it when I talk with engineers.
