### ISSUE TITLE
Review Request - Spring Boot Conventions and sub-pages

### ISSUE THREAD

**Issue by heyjcollins** [pivotal/docs-tap#556]
My team has completed an initial draft of the Spring Boot Conventions component docs.
English is not the primary language of person who drafted them.
Could someone from docs please review the following pages and make any corrections in syntax/grammer/tense, etc... so the information can be more readily consumed?

The pages in question can be found in this directly and below:
/docs-tap/spring-boot-conventions/

If you have any questions please feel free to reach out to me directly on slack!

**Comment by snneji** [comment]
This is old and has likely been done. Closing.
