### ISSUE TITLE
Improve "Install Application Accelerator" steps

### ISSUE THREAD

**Issue by KeithRichardLee** [pivotal/docs-tap#56]
Like ticket x,  remove steps 1 & 2. If its decided to keep the steps, then add the commands here rather than jumping back and forth to work it out.

For step 5, potentially add the details/steps here so less linking out. Also, I had to read the linked section until found steps (step 9) on sample accelerators. Not a great UX.

**Comment by jncd** [comment]
Step 5 got fixed: https://docs.vmware.com/en/VMware-Tanzu-Application-Platform/0.1/tap-0-1/GUID-install.html#install-application-accelerator-11

As to the steps 1 & 2, you make a good point and the current mess of installation instructions is very hard to make out: https://docs-staging.vmware.com/en/VMware-Tanzu-Application-Platform/0.2/tap-0-2/GUID-install.html#install-cloud-native-runtimes-3 
We'll have to wait until the dust settles before we can take a stab at something sensible.
