### ISSUE TITLE
Improve "Deploying the Spring Pet Clinic App"

### ISSUE THREAD

**Issue by KeithRichardLee** [pivotal/docs-tap#57]
Add steps on how to access Application Accelerator eg run "kubectl get -n accelerator-system service" and use external ip returned for the acc-ui-server

re step 1 "Use the "Spring PetClinic sample Accelerator to generate a new project called spring-petclinic-eks and download the zip file".... suggest to rename "spring-petclinic-eks" so we are not a free advertising agency for our competition! Update screengrab and steps throughout

re step 3, add more details here and separate out the steps from the code block eg show contents of "tap-sa.yaml" and then the individual kubectl commands 

re step 3, call out that user has to update the yaml to include their own registry.  The example is very confusing as its an internal private registry in VMware folk wont have access to. 

re step 3, call out to enter registry credentials

re step 4, like above, breakdown the huge code block into individual blocks of yaml and commands etc

re step 4, call out to replace registry with users registry

re step 4, call out to replace git url with users git repo

re step 5, like above, breakdown the huge code block into individual blocks of yaml and commands etc and also fix indentation.

re step 5, call out to replace registry with users registry

**Comment by jncd** [comment]
We were told to delete the (unfortunate) tutorial for beta-2. It should be replaced with improved "Getting Started" content: https://docs.google.com/document/d/1oTeV-BCayKynLAWu0zluCPCuo55vrU8cPkU3CYCyC5Y/edit?usp=sharing
