### ISSUE TITLE
Add some troubleshooting steps at end of tutorial

### ISSUE THREAD

**Issue by KeithRichardLee** [pivotal/docs-tap#58]
Throughout the tutorial there are no indications that all steps are working as planned until the very end where you have to verify you can access the app. Suggest to add troubleshooting tips or link to appendix with them.

**Comment by jncd** [comment]
We were told to delete the (unfortunate) tutorial for beta-2. It should be replaced with improved "Getting Started" content: https://docs.google.com/document/d/1oTeV-BCayKynLAWu0zluCPCuo55vrU8cPkU3CYCyC5Y/edit?usp=sharing
