### ISSUE TITLE
Add note re app showing in App Live View

### ISSUE THREAD

**Issue by KeithRichardLee** [pivotal/docs-tap#59]
At end of tutorial add a note that the app wont show in App Live View if it has scaled to zero. Therefore access the app and it will then show in App Live View again.

**Comment by jncd** [comment]
We were told to delete the (unfortunate) tutorial for beta-2. It should be replaced with improved "Getting Started" content: https://docs.google.com/document/d/1oTeV-BCayKynLAWu0zluCPCuo55vrU8cPkU3CYCyC5Y/edit?usp=sharing
