### ISSUE TITLE
Improve making code changes section in tutorial

### ISSUE THREAD

**Issue by KeithRichardLee** [pivotal/docs-tap#60]
breakdown the huge code block into separate detailed steps and where each command can be copied easily using the doc copy button

add step to navigate to folder where app resides

reduce number of steps by opening file using full path

clearly show what was changed in the vetlist.html file

clearly highlight that image in kapp-deploy-spring-petclinic.yaml needs to be updated with new image

**Comment by jncd** [comment]
We were told to delete the (unfortunate) tutorial for beta-2. It should be replaced with improved "Getting Started" content: https://docs.google.com/document/d/1oTeV-BCayKynLAWu0zluCPCuo55vrU8cPkU3CYCyC5Y/edit?usp=sharing
