### ISSUE TITLE
Broken kinks in Installing individual components instruction

### ISSUE THREAD

**Issue by Shanfan** [pivotal/docs-tap#651]
I found broken links in (https://docs.vmware.com/en/VMware-Tanzu-Application-Platform/0.3/tap-0-3/GUID-install-components.html): Wherever it mentions:

> Where PACKAGE-NAME is the name of the package listed in step 5 of Add the Tanzu Application Platform Package Repository above.

It was referencing an anchor on the same page, and that anchor doesn't exist. 

The correct page should be on [this page](https://docs.vmware.com/en/VMware-Tanzu-Application-Platform/0.3/tap-0-3/GUID-install.html) and in Step 3.

**Comment by YugangW** [comment]
@Shanfan Thanks for logging this issue. It has been fixed.
