### ISSUE TITLE
Correct package name for Tanzu CLI

### ISSUE THREAD

**Issue by guidowb** [pivotal/docs-tap#66]
In [install-general](https://github.com/pivotal/docs-tap/blob/main/install-general.md#cli-and-plugin), the package name `tanzu-cli-bundle-*-amd64.tar` is incorrect for current versions. The current name is `tanzu-framework-*-amd64.tar` (for all three platforms)

**Comment by jncd** [comment]
@heyjcollins You've looked at this section recently. 
Should we do a global find-and-replace for `tanzu-cli-bundle` to `tanzu-framework`? 

Also ^^ @dhadukk

**Comment by dhadukk** [comment]
Hi @jncd  Yes Please replace it with tanzu-framework-*-amd64.tar. Thank you.

**Comment by jncd** [comment]
@guidowb and @dhadukk Looks like someone already did this. Perhaps during the bug bash. Great! I'm closing this now.
