### ISSUE TITLE
Add link to next steps at bottom of install Part I

### ISSUE THREAD

**Issue by guidowb** [pivotal/docs-tap#67]
After going through [Part I](https://github.com/pivotal/docs-tap/blob/main/install-general.md), I found myself wondering "what's next". Maybe add a "Now you're ready to proceed to Part II" with a link at the bottom of that page?

**Comment by jncd** [comment]
Hi @guidowb 
I was thinking this myself. Thanks for the confirmation.
I've made a story in our tracker to address. 

https://www.pivotaltracker.com/story/show/179754895
