### ISSUE TITLE
Missing prerequisite Tanzu CLI plugin

### ISSUE THREAD

**Issue by guidowb** [pivotal/docs-tap#69]
After installing prereqs per [Part I](https://github.com/pivotal/docs-tap/blob/main/install-general.md#set-and-verify), the first use of the Tanzu CLI in [Part II](https://github.com/pivotal/docs-tap/blob/main/install.md) depends on a plug-in for imagepullsecret that was downloaded but not installed.

The missing command is
```
tanzu plugin install --local ./cli imagepullsecret
```

**Comment by jncd** [comment]
Thanks @guidowb 
Hello SME team, Please would you address this issue for Guido (and all our users).
@Agnishwar2021 @msrinivasssa @dhadukk @bindu-tg @vdesikanvmware

**Comment by msrinivasssa** [comment]
@guidowb - imagepullsecret plugin is not available in tanzu-framework-0.4.0. we'll be updating the TAP page with latest bundles tomorrow which will have the plugin available. Docs will also be updated with the latest version accordingly.

**Comment by jncd** [comment]
Thanks so much @msrinivasssa 
I'll be ready to merge your docs PR tomorrow. 😀 
I'll mark this issue as closed for now.
