### ISSUE TITLE
Need instructions on how to find the value for TAP-REPO-IMGPKG

### ISSUE THREAD

**Issue by guidowb** [pivotal/docs-tap#70]
Step 3 of Add the Tanzu Application Platform Package Repository on [this page](https://github.com/pivotal/docs-tap/blob/main/install.md) explains that "TAP-REPO-IMGPKG is the Tanzu Application Platform repo bundle artifact reference". While it continues to give an example (`registry.tanzu.vmware.com/tanzu-application-platform/tap-packages:0.2.0`), that specific url is not currently correct, and most users won't know how to find the working one by finding the tap-package-repo-bundle download on TanzuNet.

**Comment by jncd** [comment]
@msrinivasssa 
Are you able to fix this one as well?

**Comment by Agnishwar2021** [comment]
@jncd Can we make this doc available only by 10/1 when Bug Bash starts. We are in the process of building the TAP Beta 2 Repo, unless that is completed we will not be able to provide the content that works for user.

**Comment by jncd** [comment]
Hi @Agnishwar2021 
I'm not quite sure what you mean "about making the doc available." I think that the answer is yes. 
I've been updating the docs at https://docs-staging.vmware.com/en/VMware-Tanzu-Application-Platform/0.2/tap-0-2/GUID-install.html several times a day lately — so much is changing.

**Comment by jncd** [comment]
Hi @guidowb 

I just got confirmation from Kinjal that this issue is fixed now in the docs.
