### ISSUE TITLE
TAP Conceptual Image has status indicators (harvey balls) that should not be public facing

### ISSUE THREAD

**Issue by dbbaskette** [pivotal/docs-tap#879]
images/tap-conceptual-value.jpg

This image has Harvey Balls that indicate the status of progress on individual features.  They should be removed from the graphic.
https://en.wikipedia.org/wiki/Harvey_balls

**Comment by RichardJJG** [comment]
Thanks for pointing that out, @dbbaskette, an edited image will go live tomorrow.
